Repository buggregator/frontend, pull requests merged in 2023-09, with the labels that each got.

#25 Issue/#6 pause auto refresh
  .gitignore
  .idea/.gitignore
  .idea/frontend.iml
  .idea/modules.xml
  .idea/php.xml
  .idea/vcs.xml
  .storybook/preview.ts
  .storybook/stories.css
  components/PageHeader/PageHeader.stories.ts
  components/PageHeader/PageHeader.vue
  config/constants.ts
  pages/http-dumps/index.vue
  pages/index.vue
  pages/inspector/index.vue
  pages/profiler/index.vue
  pages/sentry/index.vue
  pages/smtp/index.vue
  plugins/events.client.ts
  stores/events.ts
Labels: feature, improvement, usability

#26 Issue/#17 add virtualisation
  components/PreviewCard/PreviewCard.vue
  components/PreviewEventMapper/PreviewEventMapper.stories.ts
  package.json
  yarn.lock
Labels: enhancement, usability, performance

#29 Fixes problem with bool values
  components/ValueDump/ValueDump.vue
  components/VarDumpPreview/VarDumpPreview.stories.ts
  mocks/var-dump-boolean-false.json
  mocks/var-dump-boolean-true.json
Labels: bug

#27 Issue/#6 optimize autorefresh
  config/constants.ts
  package.json
  pages/index.vue
  plugins/events.client.ts
  stores/events.ts
  stores/theme.ts
  yarn.lock
Labels: improvement, usability, performance

#32 Issue/#28 xhprof sidebar sorting
  components/ProfilerPage/ProfilerPage.vue
  components/ProfilerPageCallStack/ProfilerPageCallStack.vue
  components/ProfilerPageCallStackRow/ProfilerPageCallStackRow.vue
  components/SortWrap/SortWrap.stories.ts
  components/SortWrap/SortWrap.vue
  config/constants.ts
Labels: enhancement, usability

#31 Issue/#28 xhprof improves
  assets/digraph-builder.scss
  assets/index.css
  components/ProfilePageFlamegraph/ProfilePageFlamegraph.vue
  components/ProfilerPage/ProfilerPage.vue
  components/ProfilerPageCallGraph/ProfilerPageCallGraph.vue
  components/ProfilerPageCallStack/ProfilerPageCallStack.vue
  components/ProfilerPageCallStackRow/ProfilerPageCallStackRow.vue
  components/SortWrap/SortWrap.stories.ts
  components/SortWrap/SortWrap.vue
  config/constants.ts
Labels: enhancement, improvement, usability, performance

#35 Issue/#19 app version
  .env.sample
  components/LayoutSidebar/LayoutSidebar.vue
  nuxt.config.ts
Labels: enhancement, feature, usability

#39 Issue/#19 api version
  components/LayoutSidebar/LayoutSidebar.stories.ts
  components/LayoutSidebar/LayoutSidebar.vue
  plugins/api.client.ts
  utils/events-transport.ts
Labels: enhancement, improvement, usability

#41 [#40] Fixes problem with handling Sentry events
  components/SentryPage/SentryPage.stories.ts
  components/SentryPage/SentryPage.vue
  components/SentryPageRequest/SentryPageRequest.vue
  components/SentryPreview/SentryPreview.stories.ts
  components/SentryPreview/SentryPreview.vue
  mocks/sentry-event.json
  mocks/sentry-js-event.json
  mocks/sentry-js.json
Labels: bug
