Repository buggregator/frontend, pull requests merged in 2023-11, with the labels that each got.

#61 Implemented feature to show filename and line number at the footer of each Ray event, enhancing user visibility and debugging efficiency.
  utils/normalize-event.ts
Labels: enhancement

#64 Enhance xhprof call graph visualization
  components/ProfilePageFlamegraph/ProfilePageFlamegraph.vue
  components/ProfilerPageCallGraph/ProfilerPageCallGraph.vue
  components/RenderGraph/RenderGraph.vue
  components/StatBoard/StatBoard.vue
  config/types.ts
  utils/calc-graph-data.ts
Labels: enhancement

#65 Resolve search functionality issue as indicated by var-dump output.
  vendor/dumper.js
Labels: bug

#69 Fixes problem when render non-HTML emails
  assets/vue3-tabs-component.scss
  components/SmtpPage/SmtpPage.stories.ts
  components/SmtpPage/SmtpPage.vue
  mocks/smtp-text.json
Labels: bug, module:smtp

#72 Fixes problem with desktop preview of SMTP mail
  assets/mixins.scss
  src/screens/smtp/ui/smtp-page/smtp-page.vue
  src/shared/ui/icon-svg/icon-svg-originals/discord.svg
  src/shared/ui/icon-svg/icon-svg.vue
  src/widgets/ui/page-placeholder/page-placeholder-item.vue
  src/widgets/ui/page-placeholder/page-placeholder.vue
Labels: bug, enhancement, module:smtp

#73 Fixes event type for monolog
  assets/mixins.scss
  pages/smtp/[id].vue
  src/entities/monolog/lib/use-monolog/normalize-monolog.ts
Labels: bug

#75 Fixes colors in timeline for inspector module
  src/screens/inspector/ui/inspector-page-timeline/inspector-page-timeline.vue
Labels: bug, module:inspector

#76 Feature/smtp page preview impove
  src/screens/smtp/ui/smtp-page-preview/smtp-page-preview.vue
Labels: bug, enhancement
