Repository buggregator/frontend, pull requests merged in 2023-10, with the labels that each got.

#46 Issue/#45 fix stop fetching
  components/PreviewCardHeader/PreviewCardHeader.vue
  config/types.ts
  pages/index.vue
  plugins/events.client.ts
  stores/cached-ids.ts
  stores/events.ts
  utils/events-transport.ts
Labels: bug, enhancement, usability

#48 Issue/#47 layout update
  assets/mixins.scss
  components/IconSvg/IconSvg.vue
  components/IconSvg/lock-off.svg
  components/IconSvg/lock.svg
  components/LayoutSidebar/LayoutSidebar.vue
  components/PageHeader/PageHeader.vue
  components/ProfilerPage/ProfilerPage.vue
  components/ProfilerPageCallGraph/ProfilerPageCallGraph.vue
  config/constants.ts
  layouts/default.vue
  pages/http-dumps/[id].vue
  pages/index.vue
  pages/inspector/[id].vue
  pages/profiler/[id].vue
  pages/sentry/[id].vue
  pages/settings.vue
  pages/smtp/[id].vue
  stores/settings.ts
  stores/theme.ts
Labels: bug, improvement, usability

#50 Adds GH action to build dev image based on a prerelease
  .github/workflows/docker-dev-image.yml
Labels: enhancement

#49 Issue/#33 improve callgrph performance
  assets/digraph-builder.scss
  assets/index.css
  components/ProfilerPage/ProfilerPage.vue
  components/ProfilerPageCallGraph/ProfilerPageCallGraph.vue
  components/RenderGraph/RenderGraph.stories.ts
  components/RenderGraph/RenderGraph.vue
  components/StatBoard/StatBoard.vue
  config/types.ts
  nuxt.config.ts
  package.json
  utils/calc-graph-data.ts
  utils/digraph-builder.ts
  yarn.lock
Labels: bug, module:xhprof, improvement, performance

#52 Issue/#33 improve callgraph usability
  components/ProfilerPage/ProfilerPage.vue
  components/ProfilerPageCallGraph/ProfilerPageCallGraph.vue
  components/RenderGraph/RenderGraph.vue
Labels: bug, enhancement, usability, module:events

#54 Issue/#43 rest fallback on ws connection fail
  components/HttpDumpPage/HttpDumpPage.vue
  components/LayoutSidebar/LayoutSidebar.vue
  components/PreviewCard/PreviewCard.vue
  components/RayDumpPreview/RayTypesPreview/LockPayload.vue
  components/SmtpAttachment/SmtpAttachment.stories.ts
  components/SmtpAttachment/SmtpAttachment.vue
  components/SmtpPage/SmtpPage.vue
  config/types.ts
  layouts/default.vue
  pages/http-dumps/[id].vue
  pages/inspector/[id].vue
  pages/profiler/[id].vue
  pages/sentry/[id].vue
  pages/smtp/[id].vue
  plugins/api.client.ts
  plugins/events.client.ts
  stores/cached-ids.ts
  stores/connections.ts
  stores/events.ts
  utils/api-transport.ts
  utils/events-transport.ts
  utils/io/centrifuge.ts
  utils/io/constants.ts
  utils/io/events-requests.ts
  utils/io/index.ts
  utils/io/logger.ts
  utils/io/types.ts
Labels: enhancement, feature, usability, module:events, performance

#53 Improvements for the issue #33
  components/ProfilerPageCallGraph/ProfilerPageCallGraph.vue
  components/RenderGraph/RenderGraph.vue
Labels: enhancement

#56 Issue/#55 fix preview horizontal scroll
  components/RayDumpPreview/RayTypesPreview/CallerPayload.vue
  components/RayDumpPreview/RayTypesPreview/EloquentPayload.vue
  components/RayDumpPreview/RayTypesPreview/EventPayload.vue
  components/RayDumpPreview/RayTypesPreview/QueryPayload.vue
  components/RayDumpTypeMapper/RayDumpTypeMapper.vue
  components/SentryPreview/SentryPreview.vue
  config/constants.ts
Labels: bug
