Repository buggregator/frontend, pull requests merged in 2024-06, with the labels that each got.

#159 [#157] fix pause removing on empty page
  src/shared/ui/pause-button/pause-button.stories.ts
  src/shared/ui/pause-button/pause-button.vue
  src/widgets/ui/page-layout/page-layout.vue
Labels: bug

#160 [#154] add var-dump label
  src/entities/var-dump/lib/normalize-var-dump-event.ts
  src/entities/var-dump/types.ts
Labels: feature, improvement

#163 Refactors profiler module
  package.json
  pages/profiler/[id].vue
  src/entities/inspector/ui/preview-card/preview-card.vue
  src/entities/profiler/types.ts
  src/entities/profiler/ui/preview-card/preview-card.vue
  src/entities/sentry/ui/preview-card/preview-card.vue
  src/entities/sentry/ui/sentry-exception/sentry-exception.vue
  src/entities/smtp/ui/preview-card/preview-card.vue
  src/features/lib/cytoscape/prepare-data.ts
  src/features/lib/cytoscape/types.ts
  src/features/lib/cytoscape/use-cytoscape.ts
  src/features/lib/flame-chart/build.ts
  src/features/lib/flame-chart/index.ts
  src/screens/profiler/ui/call-graph-toolbar/call-graph-toolbar.vue
  src/screens/profiler/ui/call-graph-toolbar/index.ts
  src/screens/profiler/ui/call-graph/call-graph.vue
  src/screens/profiler/ui/flame-graph/flame-graph.vue
  src/screens/profiler/ui/profiler-page/profiler-page.vue
  src/screens/profiler/ui/top-functions/index.ts
  src/screens/profiler/ui/top-functions/top-functions.vue
  src/screens/smtp/ui/smtp-page/smtp-page.vue
  src/shared/lib/formats/format-file-size.ts
  src/shared/types/partials.ts
  src/shared/ui/stat-board/stat-board.vue
  yarn.lock
Labels: enhancement, module:xhprof, improvement, usability

#165 Sets Wall Time as a default metric for call graph profiler
  src/screens/profiler/ui/call-graph/call-graph.vue
Labels: module:xhprof, usability

#164 Fixed Profiler popup Stat-board issues:
  src/screens/profiler/ui/call-stat-board/call-stat-board.vue
  src/screens/profiler/ui/flame-graph/flame-graph.vue
  src/shared/ui/stat-board/stat-board.vue
Labels: bug, module:xhprof, usability

#169 Issue/#168 http dump page
  middleware/auth.global.ts
  pages/http-dump/[id].vue
  pages/http-dump/index.vue
  plugins/auth.ts
  src/shared/ui/icon-svg/icon-svg.vue
  src/widgets/ui/layout-sidebar/layout-sidebar.vue
Labels: bug, module:http-dump

#171 Issue/#166 update var dump context
  src/screens/var-dump/ui/var-dump-page/var-dump-page.vue
  src/shared/ui/preview-card/preview-card-footer.vue
Labels: module:var-dumper, improvement

#170 #162 fix smtp attachment link
  src/screens/smtp/ui/smtp-page/smtp-page.vue
  src/shared/ui/file-attachment/file-attachment.vue
Labels: bug, module:smtp

#176 #158 update event show animation
  src/entities/http-dump/ui/preview-card/preview-card.vue
  src/entities/inspector/ui/preview-card/preview-card.vue
  src/entities/monolog/ui/preview-card/preview-card.vue
  src/entities/profiler/ui/preview-card/preview-card.vue
  src/entities/sentry/ui/preview-card/preview-card.vue
  src/entities/smtp/ui/preview-card/preview-card.vue
  src/entities/var-dump/ui/preview-card/preview-card.vue
  src/shared/ui/preview-card/preview-card.vue
Labels: enhancement, usability

#179 Issue/#156 events counters
  pages/settings.vue
  src/shared/constants/index.ts
  src/shared/constants/pages.ts
  src/shared/lib/use-events/use-events-api.ts
  src/shared/lib/use-events/use-events.ts
  src/shared/stores/cached-ids.ts
  src/shared/stores/events.ts
  src/shared/stores/settings.ts
  src/shared/types/local-storage.ts
  src/shared/ui/badge-number/badge-number.stories.ts
  src/shared/ui/badge-number/badge-number.vue
  src/shared/ui/badge-number/index.ts
  src/shared/ui/index.ts
  src/widgets/ui/layout-sidebar/constants.ts
  src/widgets/ui/layout-sidebar/layout-sidebar.vue
  src/widgets/ui/page-event-header/page-event-header.vue
  src/widgets/ui/page-header/page-header.vue
  src/widgets/ui/page-layout/page-layout.vue
Labels: feature, usability, module:events

#180 Issue/#177 fix page titles
  package.json
  pages/http-dump/[id].vue
  pages/inspector/[id].vue
  pages/monolog/[id].vue
  pages/profiler/[id].vue
  pages/ray/[id].vue
  pages/sentry/[id].vue
  pages/settings.vue
  pages/smtp/[id].vue
  pages/var-dump/[id].vue
  src/widgets/ui/page-layout/page-layout.vue
  yarn.lock
Labels: bug

#181 update storybook varsion
  .storybook/preview.ts
  .storybook/stories.css
  nuxt.config.ts
  package.json
  src/shared/ui/icon-svg/icon-svg.stories.ts
  src/widgets/ui/page-layout/page-layout.stories.ts
  yarn.lock
Labels: improvement

#184 Issue/#183 fix pause functionality
  src/shared/constants/pages.ts
  src/shared/lib/use-api-transport/use-api-transport.ts
  src/shared/lib/use-events/use-events-api.ts
  src/shared/lib/use-events/use-events.ts
  src/shared/stores/cached-ids.ts
  src/shared/stores/events.ts
  src/shared/stores/events/events-store.ts
  src/shared/stores/events/index.ts
  src/shared/stores/events/local-storage-actions.ts
  src/shared/stores/events/types.ts
  src/shared/stores/index.ts
  src/shared/stores/locked-ids.ts
  src/shared/types/index.ts
  src/shared/types/pages.ts
  src/widgets/ui/page-layout/page-layout.vue
Labels: bug, improvement

#182 Dx/update page layouts
  .storybook/preview.ts
  app.vue
  layouts/default.vue
  pages/http-dump/[id].vue
  pages/http-dump/index.vue
  pages/index.vue
  pages/inspector/[id].vue
  pages/inspector/index.vue
  pages/login.vue
  pages/monolog/[id].vue
  pages/monolog/index.vue
  pages/profiler/[id].vue
  pages/profiler/index.vue
  pages/ray/[id].vue
  pages/ray/index.vue
  pages/sentry/[id].vue
  pages/sentry/index.vue
  pages/settings.vue
  pages/smtp/[id].vue
  pages/smtp/index.vue
  pages/var-dump/[id].vue
  pages/var-dump/index.vue
  src/assets/mixins.scss
  src/screens/ray/ui/ray-page/ray-page.vue
  src/screens/var-dump/ui/var-dump-page/var-dump-page.vue
  src/shared/constants/pages.ts
  src/shared/ui/app-header/app-header.stories.ts
  src/shared/ui/app-header/app-header.vue
  src/shared/ui/app-header/index.ts
  src/shared/ui/index.ts
  src/widgets/ui/index.ts
  src/widgets/ui/layout-sidebar/layout-sidebar.vue
  src/widgets/ui/page-event-header/page-event-header.vue
  src/widgets/ui/page-header/page-header.stories.ts
  src/widgets/ui/page-header/page-header.vue
  src/widgets/ui/page-layout/page-layout.vue
Labels: improvement, usability
