Repository buggregator/frontend, pull requests merged in 2024-03, with the labels that each got.

#113 fix ws reconnections calls
  src/shared/lib/io/centrifuge.ts
Labels: bug

#116 Optimize styles for various screen sizes
  assets/mixins.scss
  pages/index.vue
  src/entities/http-dump/ui/preview-card/preview-card.vue
  src/entities/inspector/ui/inspector-stat-board/inspector-stat-board.vue
  src/entities/ray/mocks/index.ts
  src/entities/ray/mocks/ray-boolean-false.json
  src/entities/ray/mocks/ray-boolean-true.json
  src/entities/ray/ui/preview-card/preview-card.stories.ts
  src/entities/ray/ui/ray-custom/ray-custom.vue
  src/entities/ray/ui/ray-exception/ray-exception.vue
  src/entities/smtp/ui/preview-card/preview-card.vue
  src/shared/ui/pause-button/pause-button.vue
  src/shared/ui/preview-card/preview-card-footer.vue
  src/shared/ui/preview-card/preview-card-header.vue
  src/shared/ui/preview-card/preview-card.vue
  src/shared/ui/stat-board/stat-board.vue
  src/shared/ui/value-dump/value-dump.vue
  src/widgets/ui/layout-sidebar/layout-sidebar.vue
  src/widgets/ui/page-header/page-header.vue
  src/widgets/ui/page-placeholder/page-placeholder-item.vue
  src/widgets/ui/page-placeholder/page-placeholder.vue
Labels: bug, enhancement, improvement

#117 Fixes problem with subscribing WS events
  .docker/Dockerfile
  assets/mixins.scss
  src/shared/lib/io/logger.ts
  src/shared/lib/use-api-transport/use-api-transport.ts
  src/shared/ui/preview-card/preview-card-header.vue
  src/shared/ui/preview-card/preview-card.vue
  src/widgets/ui/layout-sidebar/layout-sidebar.vue
  src/widgets/ui/page-header/page-header.vue
  stores/settings.ts
Labels: bug, enhancement
